import { useState } from 'react'
import { Modal } from '@/components/ui/Modal'
import { Button } from '@/components/ui/Button'
import { createClient as createVeilClient } from '@supabase/supabase-js'
import { useUIStore } from '@/store/ui'
import { v4 as uuidv4 } from 'uuid'

const veilSupabase = createVeilClient(
  process.env.NEXT_PUBLIC_VEIL_SUPABASE_URL || 'https://hvsexqyieibkspnnvigd.supabase.co',
  process.env.NEXT_PUBLIC_VEIL_SUPABASE_ANON_KEY || ''
)

interface Props {
  onClose: () => void
  onSuccess: (newSub: any) => void
}

export function CreateVpnSubModal({ onClose, onSuccess }: Props) {
  const [username, setUsername] = useState('')
  const [telegram, setTelegram] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const addToast = useUIStore(s => s.addToast)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    // Auto-generate username if empty
    const finalUsername = username.trim() 
      ? username.trim() 
      : `Client-${Math.floor(1000 + Math.random() * 9000)}`

    setIsSubmitting(true)
    try {
      // 1. Создаем профиль
      const { data: profile, error: profileErr } = await veilSupabase
        .from('profiles')
        .insert({
          username: finalUsername,
          telegram_username: telegram.trim() ? telegram.replace('@', '') : null
        })
        .select()
        .single()

      if (profileErr) throw profileErr

      // 2. Создаем подписку на 1 месяц (500GB)
      const token = uuidv4().replace(/-/g, '')
      const subKey = uuidv4() // Temporary client ID. Real VLESS key generated by sync.js

      const expires = new Date()
      expires.setMonth(expires.getMonth() + 1)

      const { data: sub, error: subErr } = await veilSupabase
        .from('subscriptions')
        .insert({
          user_id: profile.id,
          token: token,
          subscription_key: subKey,
          status: 'active',
          traffic_limit: 536870912000, // 500GB
          expires_at: expires.toISOString()
        })
        .select()
        .single()

      if (subErr) throw subErr

      // Подготавливаем объект для добавления в таблицу на UI
      const formattedSub = {
        id: sub.id,
        user_id: profile.id,
        username: profile.username,
        telegram_username: profile.telegram_username,
        status: sub.status,
        expires_at: sub.expires_at,
        traffic_used: 0,
        traffic_limit: sub.traffic_limit,
        subscription_key: sub.subscription_key,
        token: sub.token,
        tg_bot_linked: false,
        tg_channel_subscribed: false
      }

      onSuccess(formattedSub)
      addToast('Успешно', 'Новый пользователь VPN создан!', 'ok')
      onClose()
    } catch (err: any) {
      console.error(err)
      addToast('Ошибка', err.message || 'Произошла ошибка', 'err')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Modal title="Создать пользователя VPN" onClose={onClose}>
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-[11.5px] uppercase tracking-[0.1em] text-mute2 font-semibold mb-2">
            Имя клиента (необязательно)
          </label>
          <input
            autoFocus
            value={username}
            onChange={e => setUsername(e.target.value)}
            className="w-full h-10 px-3.5 rounded-xl bg-bg/40 border border-line focus:border-accent/60 outline-none text-[13.5px] placeholder:text-mute2 transition-all"
            placeholder="Сгенерируется автоматически, если оставить пустым"
          />
        </div>

        <div>
          <label className="block text-[11.5px] uppercase tracking-[0.1em] text-mute2 font-semibold mb-2">
            Telegram Username (необязательно)
          </label>
          <input
            value={telegram}
            onChange={e => setTelegram(e.target.value)}
            className="w-full h-10 px-3.5 rounded-xl bg-bg/40 border border-line focus:border-accent/60 outline-none text-[13.5px] placeholder:text-mute2 transition-all"
            placeholder="@username"
          />
        </div>

        <div className="pt-2 flex justify-end gap-3">
          <Button type="button" variant="ghost" onClick={onClose}>
            Отмена
          </Button>
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting ? 'Создание...' : 'Создать подписку'}
          </Button>
        </div>
      </form>
    </Modal>
  )
}
